name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download proxy list 1
        run: |
          curl -o proxy_list_1.txt https://raw.githubusercontent.com/h58fmb0344g9h3/p57gdv3j3n0vg334/refs/heads/main/f74bjd2h2ko99f3j5

      - name: Download proxy list 2
        run: |
          curl -o proxy_list_2.txt https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt

      - name: Combine, deduplicate by IP/Port, and then filter by ISP
        run: |
          cat proxy_list_1.txt proxy_list_2.txt > combined_proxies_raw.txt
          awk -F, '!seen[$1","$2]++' combined_proxies_raw.txt > unique_ip_port_proxies.txt
          awk -F, '!seen_isp[$4]++' unique_ip_port_proxies.txt > proxy_ip.txt

      - name: Create total.txt with proxy count per country
        run: |
          awk -F, '{count[$3]++} END {for (country in count) print country " : " count[country] " PROXY"}' proxy_ip.txt | sort > total.txt

      - name: Create proxy_list.json
        run: |
          # Install jq if not already available (common on ubuntu-latest runners)
          sudo apt-get update && sudo apt-get install -y jq

          # Initialize an empty JSON object
          echo "{}" > proxy_list.json

          # Read proxy_ip.txt line by line and populate the JSON
          while IFS=',' read -r ip port country isp; do
            # Combine IP and Port
            ip_port="${ip}:${port}"
            
            # Add the ip:port to the corresponding country array in JSON
            # If the country key doesn't exist, it will be created as an empty array first
            # Then the ip:port is appended
            jq --arg country "$country" --arg ip_port "$ip_port" \
              'if .[$country] then .[$country] += [$ip_port] else .[$country] = [$ip_port] end' \
              proxy_list.json > tmp.json && mv tmp.json proxy_list.json
          done < proxy_ip.txt

      - name: Upload combined proxy list as artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-proxy-list
          path: proxy_ip.txt
          retention-days: 7

      - name: Upload proxy_list.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy-list-json
          path: proxy_list.json
          retention-days: 7

      - name: Commit and push changes (optional)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add proxy_ip.txt total.txt proxy_list.json # Menambahkan proxy_list.json ke staging area
          git commit -m "Update proxy_ip.txt, total.txt, and proxy_list.json with latest combined lists, deduplicated by IP/Port, and filtered by unique ISP" || echo "No changes to commit"
          git push
