name: Process Proxy List

on:
  push:
    branches:
      - main # Ganti dengan branch yang relevan jika bukan 'main'
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual dari GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Create proxy_ip.txt (for demonstration)
      run: |
        echo "192.168.1.1,8080,US" > proxy_ip.txt
        echo "10.0.0.5,3128,ID" >> proxy_ip.txt
        echo "192.168.1.2,8081,US" >> proxy_ip.txt
        echo "172.16.0.10,8888,JP" >> proxy_ip.txt
        echo "203.0.113.1,80,GB" >> proxy_ip.txt
      # Anda bisa menghapus langkah ini jika file proxy_ip.txt sudah ada di repositori Anda.
      # Pastikan proxy_ip.txt di-commit ke repositori Anda.

    - name: Process Proxy Data with Bash and jq
      id: process_proxy
      run: |
        proxy_data_json="{}"

        while IFS=, read -r ip_part port_part country_code_part || [[ -n "$ip_part" ]]; do
            # Hapus spasi di awal/akhir jika ada
            ip_port=$(echo "${ip_part}:${port_part}" | xargs)
            country_code=$(echo "${country_code_part}" | xargs)

            if [ -n "$ip_port" ] && [ -n "$country_code" ]; then
                # Cek apakah country_code sudah ada sebagai kunci di proxy_data_json
                # Jika tidak ada, inisialisasi sebagai array kosong
                if ! echo "$proxy_data_json" | jq -e "has(\"$country_code\")" > /dev/null; then
                    proxy_data_json=$(echo "$proxy_data_json" | jq ". \"$country_code\" = []")
                fi

                # Tambahkan ip_port ke array yang sesuai dengan country_code
                proxy_data_json=$(echo "$proxy_data_json" | jq ". \"$country_code\" += [\"$ip_port\"]")
            fi
        done < proxy_ip.txt

        # Simpan hasil ke proxy_list.json dengan indentasi 2
        echo "$proxy_data_json" | jq '.' > proxy_list.json

        echo "Generated proxy_list.json:"
        cat proxy_list.json

    - name: Upload proxy_list.json artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxy-list-json
        path: proxy_list.json
