name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write # Memberikan izin tulis ke GITHUB_TOKEN untuk mengakses konten repositori

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download proxy list 1
      run: |
        curl -o proxy_list_1.txt https://raw.githubusercontent.com/h58fmb0344g9h3/p57gdv3j3n0vg334/refs/heads/main/f74bjd2h2ko99f3j5

    - name: Download proxy list 2
      run: |
        curl -o proxy_list_2.txt https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt

    - name: Combine, deduplicate by IP/Port, and then filter by ISP
      run: |
        # Menggabungkan dan menduplikasi berdasarkan IP dan Port terlebih dahulu
        cat proxy_list_1.txt proxy_list_2.txt > combined_proxies_raw.txt
        awk -F, '!seen[$1","$2]++' combined_proxies_raw.txt > unique_ip_port_proxies.txt

        # Sekarang, filter berdasarkan ISP. Ambil baris pertama untuk setiap ISP unik.
        # Kolom ke-4 adalah ISP
        awk -F, '!seen_isp[$4]++' unique_ip_port_proxies.txt > proxy_ip.txt

    - name: Create total.txt with proxy count per country
      run: |
        # Mengambil kode negara (kolom ke-3), menghitung kemunculannya, dan memformat output
        awk -F, '{count[$3]++} END {for (country in count) print country " : " count[country] " PROXY"}' proxy_ip.txt | sort > total.txt

    - name: Upload combined proxy list as artifact
      uses: actions/upload-artifact@v4
      with:
        name: combined-proxy-list
        path: proxy_ip.txt
        retention-days: 7

    - name: Commit and push changes (optional)
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add proxy_ip.txt total.txt # Menambahkan total.txt ke staging area
        git commit -m "Update proxy_ip.txt and total.txt with latest combined lists, deduplicated by IP/Port, and filtered by unique ISP" || echo "No changes to commit"
        git push
